import React from 'react'
export default class ArticleList extends React.Component{
    render(){
        return <div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
            <div>News1</div>
        </div>
    }
}